// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"math"
	"slices"
	"strconv"
	"strings"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type mQTTShadow struct {
	Broker   *string `json:"broker"    toml:"broker"    yaml:"broker"`
	ClientID *string `json:"client-id" toml:"client-id" yaml:"client-id"`
	Prefix   *string `json:"prefix"    toml:"prefix"    yaml:"prefix"`
	Username *string `json:"username"  toml:"username"  yaml:"username"`
	Password *string `json:"password"  toml:"password"  yaml:"password"`
}

type imageShadow struct {
	Projection *string  `json:"projection" toml:"projection" yaml:"projection"`
	FOV        *float64 `json:"fov"        toml:"fov"        yaml:"fov"`
	Format     *string  `json:"format"     toml:"format"     yaml:"format"`
	Width      *int     `json:"width"      toml:"width"      yaml:"width"`
	Height     *int     `json:"height"     toml:"height"     yaml:"height"`
	Stretch    *string  `json:"stretch"    toml:"stretch"    yaml:"stretch"`
	MinCut     *float64 `json:"min-cut"    toml:"min-cut"    yaml:"min-cut"`
	MaxCut     *float64 `json:"max-cut"    toml:"max-cut"    yaml:"max-cut"`
	HiPS       *string  `json:"hips"       toml:"hips"       yaml:"hips"`
}

type publicFrameShadow struct {
	StackerURL      *string `json:"stacker-url"      toml:"stacker-url"      yaml:"stacker-url"`
	PublicURL       *string `json:"public-url"       toml:"public-url"       yaml:"public-url"`
	IntervalSeconds *int    `json:"interval-seconds" toml:"interval-seconds" yaml:"interval-seconds"`
	TimeoutSeconds  *int    `json:"timeout-seconds"  toml:"timeout-seconds"  yaml:"timeout-seconds"`
}

type configShadow struct {
	LogLevel           *string            `json:"log-level"            toml:"log-level"            yaml:"log-level"`
	Port               *int               `json:"port"                 toml:"port"                 yaml:"port"`
	MQTT               *mQTTShadow        `json:"mqtt"                 toml:"mqtt"                 yaml:"mqtt"`
	Image              *imageShadow       `json:"image"                toml:"image"                yaml:"image"`
	CORSAllowedOrigins *[]string          `json:"cors-allowed-origins" toml:"cors-allowed-origins" yaml:"cors-allowed-origins"`
	PublicFrame        *publicFrameShadow `json:"public-frame"         toml:"public-frame"         yaml:"public-frame"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}

func configApplyDefaults(cfg *Config, sep string, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("log-level", configulator.LayerDefault, "default tag")
	cfg.Port = 8080
	set("port", configulator.LayerDefault, "default tag")
	cfg.MQTT.ClientID = "wheresmyscope"
	set("mqtt.client-id", configulator.LayerDefault, "default tag")
	cfg.MQTT.Prefix = "wheresmyscope"
	set("mqtt.prefix", configulator.LayerDefault, "default tag")
	cfg.Image.Projection = ProjectionType("STG")
	set("image.projection", configulator.LayerDefault, "default tag")
	cfg.Image.FOV = 3.3
	set("image.fov", configulator.LayerDefault, "default tag")
	cfg.Image.Format = ImageFormat("png")
	set("image.format", configulator.LayerDefault, "default tag")
	cfg.Image.Width = 900
	set("image.width", configulator.LayerDefault, "default tag")
	cfg.Image.Height = 600
	set("image.height", configulator.LayerDefault, "default tag")
	cfg.Image.Stretch = StretchType("linear")
	set("image.stretch", configulator.LayerDefault, "default tag")
	cfg.Image.MinCut = 0.5
	set("image.min-cut", configulator.LayerDefault, "default tag")
	cfg.Image.MaxCut = 99.5
	set("image.max-cut", configulator.LayerDefault, "default tag")
	cfg.Image.HiPS = "CDS/P/DSS2/color"
	set("image.hips", configulator.LayerDefault, "default tag")
	{
		lst := impl.SplitList("https://*,http://*", sep)
		cfg.CORSAllowedOrigins = lst
		set("cors-allowed-origins", configulator.LayerDefault, "default tag")
	}
	cfg.PublicFrame.PublicURL = "https://wheresmyscope.mcswain.dev"
	set("public-frame.public-url", configulator.LayerDefault, "default tag")
	cfg.PublicFrame.IntervalSeconds = 60
	set("public-frame.interval-seconds", configulator.LayerDefault, "default tag")
	cfg.PublicFrame.TimeoutSeconds = 10
	set("public-frame.timeout-seconds", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, _ string, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("log-level", configulator.LayerFile, file)
	}
	if s.Port != nil {
		cfg.Port = *s.Port
		set("port", configulator.LayerFile, file)
	}
	if s.MQTT != nil {
		if s.MQTT.Broker != nil {
			cfg.MQTT.Broker = *s.MQTT.Broker
			set("mqtt.broker", configulator.LayerFile, file)
		}
		if s.MQTT.ClientID != nil {
			cfg.MQTT.ClientID = *s.MQTT.ClientID
			set("mqtt.client-id", configulator.LayerFile, file)
		}
		if s.MQTT.Prefix != nil {
			cfg.MQTT.Prefix = *s.MQTT.Prefix
			set("mqtt.prefix", configulator.LayerFile, file)
		}
		if s.MQTT.Username != nil {
			cfg.MQTT.Username = *s.MQTT.Username
			set("mqtt.username", configulator.LayerFile, file)
		}
		if s.MQTT.Password != nil {
			cfg.MQTT.Password = *s.MQTT.Password
			set("mqtt.password", configulator.LayerFile, file)
		}
	}
	if s.Image != nil {
		if s.Image.Projection != nil {
			cfg.Image.Projection = ProjectionType(*s.Image.Projection)
			set("image.projection", configulator.LayerFile, file)
		}
		if s.Image.FOV != nil {
			cfg.Image.FOV = *s.Image.FOV
			set("image.fov", configulator.LayerFile, file)
		}
		if s.Image.Format != nil {
			cfg.Image.Format = ImageFormat(*s.Image.Format)
			set("image.format", configulator.LayerFile, file)
		}
		if s.Image.Width != nil {
			cfg.Image.Width = *s.Image.Width
			set("image.width", configulator.LayerFile, file)
		}
		if s.Image.Height != nil {
			cfg.Image.Height = *s.Image.Height
			set("image.height", configulator.LayerFile, file)
		}
		if s.Image.Stretch != nil {
			cfg.Image.Stretch = StretchType(*s.Image.Stretch)
			set("image.stretch", configulator.LayerFile, file)
		}
		if s.Image.MinCut != nil {
			cfg.Image.MinCut = *s.Image.MinCut
			set("image.min-cut", configulator.LayerFile, file)
		}
		if s.Image.MaxCut != nil {
			cfg.Image.MaxCut = *s.Image.MaxCut
			set("image.max-cut", configulator.LayerFile, file)
		}
		if s.Image.HiPS != nil {
			cfg.Image.HiPS = *s.Image.HiPS
			set("image.hips", configulator.LayerFile, file)
		}
	}
	if s.CORSAllowedOrigins != nil {
		cfg.CORSAllowedOrigins = *s.CORSAllowedOrigins
		set("cors-allowed-origins", configulator.LayerFile, file)
	}
	if s.PublicFrame != nil {
		if s.PublicFrame.StackerURL != nil {
			cfg.PublicFrame.StackerURL = *s.PublicFrame.StackerURL
			set("public-frame.stacker-url", configulator.LayerFile, file)
		}
		if s.PublicFrame.PublicURL != nil {
			cfg.PublicFrame.PublicURL = *s.PublicFrame.PublicURL
			set("public-frame.public-url", configulator.LayerFile, file)
		}
		if s.PublicFrame.IntervalSeconds != nil {
			cfg.PublicFrame.IntervalSeconds = *s.PublicFrame.IntervalSeconds
			set("public-frame.interval-seconds", configulator.LayerFile, file)
		}
		if s.PublicFrame.TimeoutSeconds != nil {
			cfg.PublicFrame.TimeoutSeconds = *s.PublicFrame.TimeoutSeconds
			set("public-frame.timeout-seconds", configulator.LayerFile, file)
		}
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "log-level"); ok {
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "port"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: n,
				Value:  v,
			}
		}
		cfg.Port = int(p)
		set("port", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "mqtt", "broker"); ok {
		cfg.MQTT.Broker = v
		set("mqtt.broker", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "mqtt", "client-id"); ok {
		cfg.MQTT.ClientID = v
		set("mqtt.client-id", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "mqtt", "prefix"); ok {
		cfg.MQTT.Prefix = v
		set("mqtt.prefix", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "mqtt", "username"); ok {
		cfg.MQTT.Username = v
		set("mqtt.username", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "mqtt", "password"); ok {
		cfg.MQTT.Password = v
		set("mqtt.password", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "image", "projection"); ok {
		cfg.Image.Projection = ProjectionType(v)
		set("image.projection", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "image", "fov"); ok {
		p, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.fov",
				Source: n,
				Value:  v,
			}
		}
		cfg.Image.FOV = p
		set("image.fov", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "image", "format"); ok {
		cfg.Image.Format = ImageFormat(v)
		set("image.format", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "image", "width"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.width",
				Source: n,
				Value:  v,
			}
		}
		cfg.Image.Width = int(p)
		set("image.width", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "image", "height"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.height",
				Source: n,
				Value:  v,
			}
		}
		cfg.Image.Height = int(p)
		set("image.height", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "image", "stretch"); ok {
		cfg.Image.Stretch = StretchType(v)
		set("image.stretch", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "image", "min-cut"); ok {
		p, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.min-cut",
				Source: n,
				Value:  v,
			}
		}
		cfg.Image.MinCut = p
		set("image.min-cut", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "image", "max-cut"); ok {
		p, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.max-cut",
				Source: n,
				Value:  v,
			}
		}
		cfg.Image.MaxCut = p
		set("image.max-cut", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "image", "hips"); ok {
		cfg.Image.HiPS = v
		set("image.hips", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "cors-allowed-origins"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.CORSAllowedOrigins = lst
		set("cors-allowed-origins", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "public-frame", "stacker-url"); ok {
		cfg.PublicFrame.StackerURL = v
		set("public-frame.stacker-url", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "public-frame", "public-url"); ok {
		cfg.PublicFrame.PublicURL = v
		set("public-frame.public-url", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "public-frame", "interval-seconds"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "public-frame.interval-seconds",
				Source: n,
				Value:  v,
			}
		}
		cfg.PublicFrame.IntervalSeconds = int(p)
		set("public-frame.interval-seconds", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "public-frame", "timeout-seconds"); ok {
		p, err := strconv.ParseInt(v, 10, strconv.IntSize)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "public-frame.timeout-seconds",
				Source: n,
				Value:  v,
			}
		}
		cfg.PublicFrame.TimeoutSeconds = int(p)
		set("public-frame.timeout-seconds", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}

func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{
		"log-level",
		"port",
		"mqtt" + o.Separator + "broker",
		"mqtt" + o.Separator + "client-id",
		"mqtt" + o.Separator + "prefix",
		"mqtt" + o.Separator + "username",
		"mqtt" + o.Separator + "password",
		"image" + o.Separator + "projection",
		"image" + o.Separator + "fov",
		"image" + o.Separator + "format",
		"image" + o.Separator + "width",
		"image" + o.Separator + "height",
		"image" + o.Separator + "stretch",
		"image" + o.Separator + "min-cut",
		"image" + o.Separator + "max-cut",
		"image" + o.Separator + "hips",
		"cors-allowed-origins",
		"public-frame" + o.Separator + "stacker-url",
		"public-frame" + o.Separator + "public-url",
		"public-frame" + o.Separator + "interval-seconds",
		"public-frame" + o.Separator + "timeout-seconds",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "info", "Logging level for the application. One of debug, info, warn, or error")
	fs.Var(impl.NewInt(8080), names[1], "Port to listen on")
	fs.String(names[2], "", "MQTT broker address, e.g. mqtt://mqtt.example.com:1883. Required")
	fs.String(names[3], "wheresmyscope", "Client ID for MQTT connection")
	fs.String(names[4], "wheresmyscope", "Prefix for MQTT topics")
	fs.String(names[5], "", "Username for MQTT connection")
	fs.String(names[6], "", "Password for MQTT connection")
	fs.String(names[7], "STG", "Projection type. One of AZP, SZP, TAN, STG, SIN, ARC, ZEA, AIR, CYP, CEA, CAR, MER, SFL, PAR, MOL, AIT, TSC, CSC, QSC, HPX, XPH")
	fs.Float64(names[8], 3.3, "Field of view in degrees")
	fs.String(names[9], "png", "Image format. One of png, jpeg, or fits")
	fs.Var(impl.NewInt(900), names[10], "Image width in pixels")
	fs.Var(impl.NewInt(600), names[11], "Image height in pixels")
	fs.String(names[12], "linear", "Stretch type for png and jpeg images. One of power, linear, sqrt, log, or asinh")
	fs.Float64(names[13], 0.5, "Minimum value for the stretch, between 0 and 100. Only used for png and jpeg images")
	fs.Float64(names[14], 99.5, "Maximum value for the stretch, between 0 and 100. Only used for png and jpeg images")
	fs.String(names[15], "CDS/P/DSS2/color", "HiPS survey to render the image from")
	fs.StringSlice(names[16], nil, "CORS allowed origins")
	fs.Lookup(names[16]).DefValue = "[https://*,http://*]"
	fs.String(names[17], "", "astro-stacker's base URL, e.g. http://astro-stacker.astro-processing:8080; empty shows only survey images")
	fs.String(names[18], "https://wheresmyscope.mcswain.dev", "This service's public base URL, which the page loads the frame from")
	fs.Var(impl.NewInt(60), names[19], "Seconds between checks for a newer frame")
	fs.Var(impl.NewInt(10), names[20], "Seconds before a fetch from the stacker gives up and the survey image is shown")
	return nil
}

func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "log-level"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	if n := "port"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: "--" + n,
			}
		}
		cfg.Port = v
		set("port", configulator.LayerCLI, "--"+n)
	}
	if n := "mqtt" + o.Separator + "broker"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "mqtt.broker",
				Source: "--" + n,
			}
		}
		cfg.MQTT.Broker = v
		set("mqtt.broker", configulator.LayerCLI, "--"+n)
	}
	if n := "mqtt" + o.Separator + "client-id"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "mqtt.client-id",
				Source: "--" + n,
			}
		}
		cfg.MQTT.ClientID = v
		set("mqtt.client-id", configulator.LayerCLI, "--"+n)
	}
	if n := "mqtt" + o.Separator + "prefix"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "mqtt.prefix",
				Source: "--" + n,
			}
		}
		cfg.MQTT.Prefix = v
		set("mqtt.prefix", configulator.LayerCLI, "--"+n)
	}
	if n := "mqtt" + o.Separator + "username"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "mqtt.username",
				Source: "--" + n,
			}
		}
		cfg.MQTT.Username = v
		set("mqtt.username", configulator.LayerCLI, "--"+n)
	}
	if n := "mqtt" + o.Separator + "password"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "mqtt.password",
				Source: "--" + n,
			}
		}
		cfg.MQTT.Password = v
		set("mqtt.password", configulator.LayerCLI, "--"+n)
	}
	if n := "image" + o.Separator + "projection"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.projection",
				Source: "--" + n,
			}
		}
		cfg.Image.Projection = ProjectionType(v)
		set("image.projection", configulator.LayerCLI, "--"+n)
	}
	if n := "image" + o.Separator + "fov"; fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.fov",
				Source: "--" + n,
			}
		}
		cfg.Image.FOV = v
		set("image.fov", configulator.LayerCLI, "--"+n)
	}
	if n := "image" + o.Separator + "format"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.format",
				Source: "--" + n,
			}
		}
		cfg.Image.Format = ImageFormat(v)
		set("image.format", configulator.LayerCLI, "--"+n)
	}
	if n := "image" + o.Separator + "width"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.width",
				Source: "--" + n,
			}
		}
		cfg.Image.Width = v
		set("image.width", configulator.LayerCLI, "--"+n)
	}
	if n := "image" + o.Separator + "height"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.height",
				Source: "--" + n,
			}
		}
		cfg.Image.Height = v
		set("image.height", configulator.LayerCLI, "--"+n)
	}
	if n := "image" + o.Separator + "stretch"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.stretch",
				Source: "--" + n,
			}
		}
		cfg.Image.Stretch = StretchType(v)
		set("image.stretch", configulator.LayerCLI, "--"+n)
	}
	if n := "image" + o.Separator + "min-cut"; fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.min-cut",
				Source: "--" + n,
			}
		}
		cfg.Image.MinCut = v
		set("image.min-cut", configulator.LayerCLI, "--"+n)
	}
	if n := "image" + o.Separator + "max-cut"; fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.max-cut",
				Source: "--" + n,
			}
		}
		cfg.Image.MaxCut = v
		set("image.max-cut", configulator.LayerCLI, "--"+n)
	}
	if n := "image" + o.Separator + "hips"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.hips",
				Source: "--" + n,
			}
		}
		cfg.Image.HiPS = v
		set("image.hips", configulator.LayerCLI, "--"+n)
	}
	if n := "cors-allowed-origins"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "cors-allowed-origins",
				Source: "--" + n,
			}
		}
		cfg.CORSAllowedOrigins = v
		set("cors-allowed-origins", configulator.LayerCLI, "--"+n)
	}
	if n := "public-frame" + o.Separator + "stacker-url"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "public-frame.stacker-url",
				Source: "--" + n,
			}
		}
		cfg.PublicFrame.StackerURL = v
		set("public-frame.stacker-url", configulator.LayerCLI, "--"+n)
	}
	if n := "public-frame" + o.Separator + "public-url"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "public-frame.public-url",
				Source: "--" + n,
			}
		}
		cfg.PublicFrame.PublicURL = v
		set("public-frame.public-url", configulator.LayerCLI, "--"+n)
	}
	if n := "public-frame" + o.Separator + "interval-seconds"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "public-frame.interval-seconds",
				Source: "--" + n,
			}
		}
		cfg.PublicFrame.IntervalSeconds = v
		set("public-frame.interval-seconds", configulator.LayerCLI, "--"+n)
	}
	if n := "public-frame" + o.Separator + "timeout-seconds"; fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "public-frame.timeout-seconds",
				Source: "--" + n,
			}
		}
		cfg.PublicFrame.TimeoutSeconds = v
		set("public-frame.timeout-seconds", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.LogLevel = &str
			default:
				return configJSONError("log-level", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError("port", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError("port", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Port = &num
			default:
				return configJSONError("port", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "mqtt":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("mqtt", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub mQTTShadow
				if err := sub.decodeJSON(dec, "mqtt"); err != nil {
					return err
				}
				s.MQTT = &sub
			}
		case "image":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("image", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub imageShadow
				if err := sub.decodeJSON(dec, "image"); err != nil {
					return err
				}
				s.Image = &sub
			}
		case "cors-allowed-origins":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError("cors-allowed-origins", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError("cors-allowed-origins"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.CORSAllowedOrigins = &out
			}
		case "public-frame":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("public-frame", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub publicFrameShadow
				if err := sub.decodeJSON(dec, "public-frame"); err != nil {
					return err
				}
				s.PublicFrame = &sub
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *mQTTShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "broker":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Broker = &str
			default:
				return configJSONError(path+".broker", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "client-id":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.ClientID = &str
			default:
				return configJSONError(path+".client-id", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "prefix":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Prefix = &str
			default:
				return configJSONError(path+".prefix", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "username":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Username = &str
			default:
				return configJSONError(path+".username", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "password":
			if err := func() error {
				v, err := dec.ReadToken()
				if err != nil {
					return err
				}
				switch v.Kind() {
				case jsontext.KindNull:
				case jsontext.KindString:
					str := v.String()
					s.Password = &str
				default:
					return configJSONError(path+".password", v, fmt.Errorf("expected a string, got %v", v.Kind()))
				}
				return nil
			}(); err != nil {
				return &configulator.ParseError{
					Err:   errors.New("invalid value"),
					Path:  path + ".password",
					Value: "(redacted)",
				}
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *imageShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "projection":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Projection = &str
			default:
				return configJSONError(path+".projection", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "fov":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				num, err := v.Float()
				if err != nil {
					return configJSONError(path+".fov", v, err)
				}
				s.FOV = &num
			default:
				return configJSONError(path+".fov", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "format":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Format = &str
			default:
				return configJSONError(path+".format", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "width":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".width", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".width", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Width = &num
			default:
				return configJSONError(path+".width", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "height":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".height", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".height", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.Height = &num
			default:
				return configJSONError(path+".height", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "stretch":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Stretch = &str
			default:
				return configJSONError(path+".stretch", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "min-cut":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				num, err := v.Float()
				if err != nil {
					return configJSONError(path+".min-cut", v, err)
				}
				s.MinCut = &num
			default:
				return configJSONError(path+".min-cut", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "max-cut":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				num, err := v.Float()
				if err != nil {
					return configJSONError(path+".max-cut", v, err)
				}
				s.MaxCut = &num
			default:
				return configJSONError(path+".max-cut", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "hips":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.HiPS = &str
			default:
				return configJSONError(path+".hips", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *publicFrameShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "stacker-url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.StackerURL = &str
			default:
				return configJSONError(path+".stacker-url", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "public-url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.PublicURL = &str
			default:
				return configJSONError(path+".public-url", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "interval-seconds":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".interval-seconds", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".interval-seconds", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.IntervalSeconds = &num
			default:
				return configJSONError(path+".interval-seconds", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		case "timeout-seconds":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindNumber:
				raw, err := v.Int()
				if err != nil {
					return configJSONError(path+".timeout-seconds", v, err)
				}
				if raw < math.MinInt || raw > math.MaxInt {
					return configJSONError(path+".timeout-seconds", v, fmt.Errorf("%d overflows int", raw))
				}
				num := int(raw)
				s.TimeoutSeconds = &num
			default:
				return configJSONError(path+".timeout-seconds", v, fmt.Errorf("expected a number, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// configJSONError returns a ParseError for the JSON token v at path.
func configJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "log-level = %v\n", c.LogLevel)
	fmt.Fprintf(&b, "port = %v\n", c.Port)
	fmt.Fprintf(&b, "mqtt.broker = %v\n", c.MQTT.Broker)
	fmt.Fprintf(&b, "mqtt.client-id = %v\n", c.MQTT.ClientID)
	fmt.Fprintf(&b, "mqtt.prefix = %v\n", c.MQTT.Prefix)
	fmt.Fprintf(&b, "mqtt.username = %v\n", c.MQTT.Username)
	b.WriteString("mqtt.password = (redacted)\n")
	fmt.Fprintf(&b, "image.projection = %v\n", c.Image.Projection)
	fmt.Fprintf(&b, "image.fov = %v\n", c.Image.FOV)
	fmt.Fprintf(&b, "image.format = %v\n", c.Image.Format)
	fmt.Fprintf(&b, "image.width = %v\n", c.Image.Width)
	fmt.Fprintf(&b, "image.height = %v\n", c.Image.Height)
	fmt.Fprintf(&b, "image.stretch = %v\n", c.Image.Stretch)
	fmt.Fprintf(&b, "image.min-cut = %v\n", c.Image.MinCut)
	fmt.Fprintf(&b, "image.max-cut = %v\n", c.Image.MaxCut)
	fmt.Fprintf(&b, "image.hips = %v\n", c.Image.HiPS)
	fmt.Fprintf(&b, "cors-allowed-origins = %v\n", c.CORSAllowedOrigins)
	fmt.Fprintf(&b, "public-frame.stacker-url = %v\n", c.PublicFrame.StackerURL)
	fmt.Fprintf(&b, "public-frame.public-url = %v\n", c.PublicFrame.PublicURL)
	fmt.Fprintf(&b, "public-frame.interval-seconds = %v\n", c.PublicFrame.IntervalSeconds)
	fmt.Fprintf(&b, "public-frame.timeout-seconds = %v\n", c.PublicFrame.TimeoutSeconds)
	return b.String()
}

func configQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
