// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	jsontext "encoding/json/jsontext"
	v2 "encoding/json/v2"
	"fmt"
	configulator "github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/spf13/pflag"
	"strconv"
	"strings"
)

type mQTTShadow struct {
	Broker   *string `json:"broker" toml:"broker" yaml:"broker"`
	ClientID *string `json:"client-id" toml:"client-id" yaml:"client-id"`
	Prefix   *string `json:"prefix" toml:"prefix" yaml:"prefix"`
	Username *string `json:"username" toml:"username" yaml:"username"`
	Password *string `json:"password" toml:"password" yaml:"password"`
}
type imageShadow struct {
	Projection *string  `json:"projection" toml:"projection" yaml:"projection"`
	FOV        *float64 `json:"fov" toml:"fov" yaml:"fov"`
	Format     *string  `json:"format" toml:"format" yaml:"format"`
	Width      *int     `json:"width" toml:"width" yaml:"width"`
	Height     *int     `json:"height" toml:"height" yaml:"height"`
	Stretch    *string  `json:"stretch" toml:"stretch" yaml:"stretch"`
	MinCut     *float64 `json:"min-cut" toml:"min-cut" yaml:"min-cut"`
	MaxCut     *float64 `json:"max-cut" toml:"max-cut" yaml:"max-cut"`
	HiPS       *string  `json:"hips" toml:"hips" yaml:"hips"`
}
type publicFrameShadow struct {
	StackerURL      *string `json:"stacker-url" toml:"stacker-url" yaml:"stacker-url"`
	PublicURL       *string `json:"public-url" toml:"public-url" yaml:"public-url"`
	IntervalSeconds *int    `json:"interval-seconds" toml:"interval-seconds" yaml:"interval-seconds"`
	TimeoutSeconds  *int    `json:"timeout-seconds" toml:"timeout-seconds" yaml:"timeout-seconds"`
}
type configShadow struct {
	LogLevel           *string            `json:"log-level" toml:"log-level" yaml:"log-level"`
	Port               *int               `json:"port" toml:"port" yaml:"port"`
	MQTT               *mQTTShadow        `json:"mqtt" toml:"mqtt" yaml:"mqtt"`
	Image              *imageShadow       `json:"image" toml:"image" yaml:"image"`
	CORSAllowedOrigins *[]string          `json:"cors-allowed-origins" toml:"cors-allowed-origins" yaml:"cors-allowed-origins"`
	PublicFrame        *publicFrameShadow `json:"public-frame" toml:"public-frame" yaml:"public-frame"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
	}
}
func configApplyDefaults(cfg *Config, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("log-level", configulator.LayerDefault, "default tag")
	cfg.Port = 8080
	set("port", configulator.LayerDefault, "default tag")
	cfg.MQTT.ClientID = "wheresmyscope"
	set("mqtt.client-id", configulator.LayerDefault, "default tag")
	cfg.MQTT.Prefix = "wheresmyscope"
	set("mqtt.prefix", configulator.LayerDefault, "default tag")
	cfg.Image.Projection = ProjectionType("STG")
	set("image.projection", configulator.LayerDefault, "default tag")
	cfg.Image.FOV = 3.3
	set("image.fov", configulator.LayerDefault, "default tag")
	cfg.Image.Format = ImageFormat("png")
	set("image.format", configulator.LayerDefault, "default tag")
	cfg.Image.Width = 900
	set("image.width", configulator.LayerDefault, "default tag")
	cfg.Image.Height = 600
	set("image.height", configulator.LayerDefault, "default tag")
	cfg.Image.Stretch = StretchType("linear")
	set("image.stretch", configulator.LayerDefault, "default tag")
	cfg.Image.MinCut = 0.5
	set("image.min-cut", configulator.LayerDefault, "default tag")
	cfg.Image.MaxCut = 99.5
	set("image.max-cut", configulator.LayerDefault, "default tag")
	cfg.Image.HiPS = "CDS/P/DSS2/color"
	set("image.hips", configulator.LayerDefault, "default tag")
	cfg.CORSAllowedOrigins = []string{"https://*", "http://*"}
	set("cors-allowed-origins", configulator.LayerDefault, "default tag")
	cfg.PublicFrame.PublicURL = "https://wheresmyscope.mcswain.dev"
	set("public-frame.public-url", configulator.LayerDefault, "default tag")
	cfg.PublicFrame.IntervalSeconds = 60
	set("public-frame.interval-seconds", configulator.LayerDefault, "default tag")
	cfg.PublicFrame.TimeoutSeconds = 10
	set("public-frame.timeout-seconds", configulator.LayerDefault, "default tag")
	return nil
}
func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, set, file)
}
func (s *configShadow) applyTo(cfg *Config, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("log-level", configulator.LayerFile, file)
	}
	if s.Port != nil {
		cfg.Port = *s.Port
		set("port", configulator.LayerFile, file)
	}
	if s.MQTT != nil {
		if s.MQTT.Broker != nil {
			cfg.MQTT.Broker = *s.MQTT.Broker
			set("mqtt.broker", configulator.LayerFile, file)
		}
		if s.MQTT.ClientID != nil {
			cfg.MQTT.ClientID = *s.MQTT.ClientID
			set("mqtt.client-id", configulator.LayerFile, file)
		}
		if s.MQTT.Prefix != nil {
			cfg.MQTT.Prefix = *s.MQTT.Prefix
			set("mqtt.prefix", configulator.LayerFile, file)
		}
		if s.MQTT.Username != nil {
			cfg.MQTT.Username = *s.MQTT.Username
			set("mqtt.username", configulator.LayerFile, file)
		}
		if s.MQTT.Password != nil {
			cfg.MQTT.Password = *s.MQTT.Password
			set("mqtt.password", configulator.LayerFile, file)
		}
	}
	if s.Image != nil {
		if s.Image.Projection != nil {
			cfg.Image.Projection = ProjectionType(*s.Image.Projection)
			set("image.projection", configulator.LayerFile, file)
		}
		if s.Image.FOV != nil {
			cfg.Image.FOV = *s.Image.FOV
			set("image.fov", configulator.LayerFile, file)
		}
		if s.Image.Format != nil {
			cfg.Image.Format = ImageFormat(*s.Image.Format)
			set("image.format", configulator.LayerFile, file)
		}
		if s.Image.Width != nil {
			cfg.Image.Width = *s.Image.Width
			set("image.width", configulator.LayerFile, file)
		}
		if s.Image.Height != nil {
			cfg.Image.Height = *s.Image.Height
			set("image.height", configulator.LayerFile, file)
		}
		if s.Image.Stretch != nil {
			cfg.Image.Stretch = StretchType(*s.Image.Stretch)
			set("image.stretch", configulator.LayerFile, file)
		}
		if s.Image.MinCut != nil {
			cfg.Image.MinCut = *s.Image.MinCut
			set("image.min-cut", configulator.LayerFile, file)
		}
		if s.Image.MaxCut != nil {
			cfg.Image.MaxCut = *s.Image.MaxCut
			set("image.max-cut", configulator.LayerFile, file)
		}
		if s.Image.HiPS != nil {
			cfg.Image.HiPS = *s.Image.HiPS
			set("image.hips", configulator.LayerFile, file)
		}
	}
	if s.CORSAllowedOrigins != nil {
		cfg.CORSAllowedOrigins = *s.CORSAllowedOrigins
		set("cors-allowed-origins", configulator.LayerFile, file)
	}
	if s.PublicFrame != nil {
		if s.PublicFrame.StackerURL != nil {
			cfg.PublicFrame.StackerURL = *s.PublicFrame.StackerURL
			set("public-frame.stacker-url", configulator.LayerFile, file)
		}
		if s.PublicFrame.PublicURL != nil {
			cfg.PublicFrame.PublicURL = *s.PublicFrame.PublicURL
			set("public-frame.public-url", configulator.LayerFile, file)
		}
		if s.PublicFrame.IntervalSeconds != nil {
			cfg.PublicFrame.IntervalSeconds = *s.PublicFrame.IntervalSeconds
			set("public-frame.interval-seconds", configulator.LayerFile, file)
		}
		if s.PublicFrame.TimeoutSeconds != nil {
			cfg.PublicFrame.TimeoutSeconds = *s.PublicFrame.TimeoutSeconds
			set("public-frame.timeout-seconds", configulator.LayerFile, file)
		}
	}
	return nil
}
func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "log-level"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.LogLevel = LogLevel(v)
			set("log-level", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "port"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "port",
					Source: n,
					Value:  v,
				}
			}
			cfg.Port = int(p)
			set("port", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "mqtt", "broker"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.MQTT.Broker = v
			set("mqtt.broker", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "mqtt", "client-id"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.MQTT.ClientID = v
			set("mqtt.client-id", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "mqtt", "prefix"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.MQTT.Prefix = v
			set("mqtt.prefix", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "mqtt", "username"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.MQTT.Username = v
			set("mqtt.username", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "mqtt", "password"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.MQTT.Password = v
			set("mqtt.password", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "image", "projection"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Image.Projection = ProjectionType(v)
			set("image.projection", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "image", "fov"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseFloat(v, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "image.fov",
					Source: n,
					Value:  v,
				}
			}
			cfg.Image.FOV = p
			set("image.fov", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "image", "format"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Image.Format = ImageFormat(v)
			set("image.format", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "image", "width"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "image.width",
					Source: n,
					Value:  v,
				}
			}
			cfg.Image.Width = int(p)
			set("image.width", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "image", "height"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "image.height",
					Source: n,
					Value:  v,
				}
			}
			cfg.Image.Height = int(p)
			set("image.height", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "image", "stretch"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Image.Stretch = StretchType(v)
			set("image.stretch", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "image", "min-cut"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseFloat(v, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "image.min-cut",
					Source: n,
					Value:  v,
				}
			}
			cfg.Image.MinCut = p
			set("image.min-cut", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "image", "max-cut"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseFloat(v, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "image.max-cut",
					Source: n,
					Value:  v,
				}
			}
			cfg.Image.MaxCut = p
			set("image.max-cut", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "image", "hips"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.Image.HiPS = v
			set("image.hips", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "cors-allowed-origins"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.CORSAllowedOrigins = configulator.SplitList(v, ec.ArraySeparator)
			set("cors-allowed-origins", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "public-frame", "stacker-url"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.PublicFrame.StackerURL = v
			set("public-frame.stacker-url", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "public-frame", "public-url"); true {
		if v, ok := ec.Getenv(n); ok {
			cfg.PublicFrame.PublicURL = v
			set("public-frame.public-url", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "public-frame", "interval-seconds"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "public-frame.interval-seconds",
					Source: n,
					Value:  v,
				}
			}
			cfg.PublicFrame.IntervalSeconds = int(p)
			set("public-frame.interval-seconds", configulator.LayerEnv, n)
		}
	}
	if n := configulator.EnvName(ec.Opts.Prefix, ec.Opts.Separator, "public-frame", "timeout-seconds"); true {
		if v, ok := ec.Getenv(n); ok {
			p, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return &configulator.ParseError{
					Err:    err,
					Path:   "public-frame.timeout-seconds",
					Source: n,
					Value:  v,
				}
			}
			cfg.PublicFrame.TimeoutSeconds = int(p)
			set("public-frame.timeout-seconds", configulator.LayerEnv, n)
		}
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}
func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	for _, name := range []string{strings.Join([]string{"log-level"}, o.Separator), strings.Join([]string{"port"}, o.Separator), strings.Join([]string{"mqtt", "broker"}, o.Separator), strings.Join([]string{"mqtt", "client-id"}, o.Separator), strings.Join([]string{"mqtt", "prefix"}, o.Separator), strings.Join([]string{"mqtt", "username"}, o.Separator), strings.Join([]string{"mqtt", "password"}, o.Separator), strings.Join([]string{"image", "projection"}, o.Separator), strings.Join([]string{"image", "fov"}, o.Separator), strings.Join([]string{"image", "format"}, o.Separator), strings.Join([]string{"image", "width"}, o.Separator), strings.Join([]string{"image", "height"}, o.Separator), strings.Join([]string{"image", "stretch"}, o.Separator), strings.Join([]string{"image", "min-cut"}, o.Separator), strings.Join([]string{"image", "max-cut"}, o.Separator), strings.Join([]string{"image", "hips"}, o.Separator), strings.Join([]string{"cors-allowed-origins"}, o.Separator), strings.Join([]string{"public-frame", "stacker-url"}, o.Separator), strings.Join([]string{"public-frame", "public-url"}, o.Separator), strings.Join([]string{"public-frame", "interval-seconds"}, o.Separator), strings.Join([]string{"public-frame", "timeout-seconds"}, o.Separator)} {
		if fs.Lookup(name) != nil {
			return fmt.Errorf("flag --%s already registered on this FlagSet", name)
		}
	}
	fs.String(strings.Join([]string{"log-level"}, o.Separator), "info", "Logging level for the application. One of debug, info, warn, or error")
	fs.Int(strings.Join([]string{"port"}, o.Separator), 8080, "Port to listen on")
	fs.String(strings.Join([]string{"mqtt", "broker"}, o.Separator), "", "MQTT broker address")
	fs.String(strings.Join([]string{"mqtt", "client-id"}, o.Separator), "wheresmyscope", "Client ID for MQTT connection")
	fs.String(strings.Join([]string{"mqtt", "prefix"}, o.Separator), "wheresmyscope", "Prefix for MQTT topics")
	fs.String(strings.Join([]string{"mqtt", "username"}, o.Separator), "", "Username for MQTT connection")
	fs.String(strings.Join([]string{"mqtt", "password"}, o.Separator), "", "Password for MQTT connection")
	fs.String(strings.Join([]string{"image", "projection"}, o.Separator), "STG", "Projection type")
	fs.Float64(strings.Join([]string{"image", "fov"}, o.Separator), 3.3, "Field of view in degrees")
	fs.String(strings.Join([]string{"image", "format"}, o.Separator), "png", "Image format")
	fs.Int(strings.Join([]string{"image", "width"}, o.Separator), 900, "Image width in pixels")
	fs.Int(strings.Join([]string{"image", "height"}, o.Separator), 600, "Image height in pixels")
	fs.String(strings.Join([]string{"image", "stretch"}, o.Separator), "linear", "Stretch type")
	fs.Float64(strings.Join([]string{"image", "min-cut"}, o.Separator), 0.5, "Minimum cut value for image processing")
	fs.Float64(strings.Join([]string{"image", "max-cut"}, o.Separator), 99.5, "Maximum cut value for image processing")
	fs.String(strings.Join([]string{"image", "hips"}, o.Separator), "CDS/P/DSS2/color", "HIPS name for the image")
	fs.StringSlice(strings.Join([]string{"cors-allowed-origins"}, o.Separator), []string{"https://*", "http://*"}, "CORS allowed origins")
	fs.String(strings.Join([]string{"public-frame", "stacker-url"}, o.Separator), "", "astro-stacker's base URL, e.g. http://astro-stacker.astro-processing:8080; empty shows only survey images")
	fs.String(strings.Join([]string{"public-frame", "public-url"}, o.Separator), "https://wheresmyscope.mcswain.dev", "This service's public base URL, which the page loads the frame from")
	fs.Int(strings.Join([]string{"public-frame", "interval-seconds"}, o.Separator), 60, "Seconds between checks for a newer frame")
	fs.Int(strings.Join([]string{"public-frame", "timeout-seconds"}, o.Separator), 10, "Seconds before a fetch from the stacker gives up and the survey image is shown")
	return nil
}
func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, set configulator.SetOrigin) error {
	if n := strings.Join([]string{"log-level"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"port"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "port",
				Source: "--" + n,
			}
		}
		cfg.Port = v
		set("port", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"mqtt", "broker"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "mqtt.broker",
				Source: "--" + n,
			}
		}
		cfg.MQTT.Broker = v
		set("mqtt.broker", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"mqtt", "client-id"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "mqtt.client-id",
				Source: "--" + n,
			}
		}
		cfg.MQTT.ClientID = v
		set("mqtt.client-id", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"mqtt", "prefix"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "mqtt.prefix",
				Source: "--" + n,
			}
		}
		cfg.MQTT.Prefix = v
		set("mqtt.prefix", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"mqtt", "username"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "mqtt.username",
				Source: "--" + n,
			}
		}
		cfg.MQTT.Username = v
		set("mqtt.username", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"mqtt", "password"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "mqtt.password",
				Source: "--" + n,
			}
		}
		cfg.MQTT.Password = v
		set("mqtt.password", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"image", "projection"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.projection",
				Source: "--" + n,
			}
		}
		cfg.Image.Projection = ProjectionType(v)
		set("image.projection", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"image", "fov"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.fov",
				Source: "--" + n,
			}
		}
		cfg.Image.FOV = v
		set("image.fov", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"image", "format"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.format",
				Source: "--" + n,
			}
		}
		cfg.Image.Format = ImageFormat(v)
		set("image.format", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"image", "width"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.width",
				Source: "--" + n,
			}
		}
		cfg.Image.Width = v
		set("image.width", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"image", "height"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.height",
				Source: "--" + n,
			}
		}
		cfg.Image.Height = v
		set("image.height", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"image", "stretch"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.stretch",
				Source: "--" + n,
			}
		}
		cfg.Image.Stretch = StretchType(v)
		set("image.stretch", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"image", "min-cut"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.min-cut",
				Source: "--" + n,
			}
		}
		cfg.Image.MinCut = v
		set("image.min-cut", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"image", "max-cut"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetFloat64(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.max-cut",
				Source: "--" + n,
			}
		}
		cfg.Image.MaxCut = v
		set("image.max-cut", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"image", "hips"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "image.hips",
				Source: "--" + n,
			}
		}
		cfg.Image.HiPS = v
		set("image.hips", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"cors-allowed-origins"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "cors-allowed-origins",
				Source: "--" + n,
			}
		}
		cfg.CORSAllowedOrigins = v
		set("cors-allowed-origins", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"public-frame", "stacker-url"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "public-frame.stacker-url",
				Source: "--" + n,
			}
		}
		cfg.PublicFrame.StackerURL = v
		set("public-frame.stacker-url", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"public-frame", "public-url"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "public-frame.public-url",
				Source: "--" + n,
			}
		}
		cfg.PublicFrame.PublicURL = v
		set("public-frame.public-url", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"public-frame", "interval-seconds"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "public-frame.interval-seconds",
				Source: "--" + n,
			}
		}
		cfg.PublicFrame.IntervalSeconds = v
		set("public-frame.interval-seconds", configulator.LayerCLI, "--"+n)
	}
	if n := strings.Join([]string{"public-frame", "timeout-seconds"}, o.Separator); fs.Changed(n) {
		v, err := fs.GetInt(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "public-frame.timeout-seconds",
				Source: "--" + n,
			}
		}
		cfg.PublicFrame.TimeoutSeconds = v
		set("public-frame.timeout-seconds", configulator.LayerCLI, "--"+n)
	}
	return nil
}
func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.LogLevel = &str
			default:
				return fmt.Errorf("log-level: expected a string, got %v", v.Kind())
			}
		case "port":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.Port = &val
			default:
				return fmt.Errorf("port: expected a number, got %v", v.Kind())
			}
		case "mqtt":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub mQTTShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.MQTT = &sub
			}
		case "image":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub imageShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.Image = &sub
			}
		case "cors-allowed-origins":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				tok, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if tok.Kind() != '[' {
					return fmt.Errorf("cors-allowed-origins: expected an array, got %v", tok.Kind())
				}
				out := []string{}
				for dec.PeekKind() != ']' {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != '"' {
						return fmt.Errorf("cors-allowed-origins: expected a string element, got %v", v.Kind())
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.CORSAllowedOrigins = &out
			}
		case "public-frame":
			if dec.PeekKind() == 'n' {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				var sub publicFrameShadow
				if err := sub.UnmarshalJSONFrom(dec); err != nil {
					return err
				}
				s.PublicFrame = &sub
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*configShadow)(nil)

func (s *mQTTShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "broker":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Broker = &str
			default:
				return fmt.Errorf("broker: expected a string, got %v", v.Kind())
			}
		case "client-id":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.ClientID = &str
			default:
				return fmt.Errorf("client-id: expected a string, got %v", v.Kind())
			}
		case "prefix":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Prefix = &str
			default:
				return fmt.Errorf("prefix: expected a string, got %v", v.Kind())
			}
		case "username":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Username = &str
			default:
				return fmt.Errorf("username: expected a string, got %v", v.Kind())
			}
		case "password":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Password = &str
			default:
				return fmt.Errorf("password: expected a string, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*mQTTShadow)(nil)

func (s *imageShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "projection":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Projection = &str
			default:
				return fmt.Errorf("projection: expected a string, got %v", v.Kind())
			}
		case "fov":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Float()
				if err != nil {
					return err
				}
				val := num
				s.FOV = &val
			default:
				return fmt.Errorf("fov: expected a number, got %v", v.Kind())
			}
		case "format":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Format = &str
			default:
				return fmt.Errorf("format: expected a string, got %v", v.Kind())
			}
		case "width":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.Width = &val
			default:
				return fmt.Errorf("width: expected a number, got %v", v.Kind())
			}
		case "height":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.Height = &val
			default:
				return fmt.Errorf("height: expected a number, got %v", v.Kind())
			}
		case "stretch":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.Stretch = &str
			default:
				return fmt.Errorf("stretch: expected a string, got %v", v.Kind())
			}
		case "min-cut":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Float()
				if err != nil {
					return err
				}
				val := num
				s.MinCut = &val
			default:
				return fmt.Errorf("min-cut: expected a number, got %v", v.Kind())
			}
		case "max-cut":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Float()
				if err != nil {
					return err
				}
				val := num
				s.MaxCut = &val
			default:
				return fmt.Errorf("max-cut: expected a number, got %v", v.Kind())
			}
		case "hips":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.HiPS = &str
			default:
				return fmt.Errorf("hips: expected a string, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*imageShadow)(nil)

func (s *publicFrameShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != '{' {
		return fmt.Errorf("expected object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == '}' {
			return nil
		}
		switch tok.String() {
		case "stacker-url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.StackerURL = &str
			default:
				return fmt.Errorf("stacker-url: expected a string, got %v", v.Kind())
			}
		case "public-url":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '"':
				str := v.String()
				s.PublicURL = &str
			default:
				return fmt.Errorf("public-url: expected a string, got %v", v.Kind())
			}
		case "interval-seconds":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.IntervalSeconds = &val
			default:
				return fmt.Errorf("interval-seconds: expected a number, got %v", v.Kind())
			}
		case "timeout-seconds":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case 'n':
			case '0':
				num, err := v.Int()
				if err != nil {
					return err
				}
				val := int(num)
				s.TimeoutSeconds = &val
			default:
				return fmt.Errorf("timeout-seconds: expected a number, got %v", v.Kind())
			}
		default:
			return fmt.Errorf("unknown key %q", tok.String())
		}
	}
}

var _ v2.UnmarshalerFrom = (*publicFrameShadow)(nil)

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c *Config) PrintConfig() string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("log-level = %v\n", c.LogLevel))
	b.WriteString(fmt.Sprintf("port = %v\n", c.Port))
	b.WriteString(fmt.Sprintf("mqtt.broker = %v\n", c.MQTT.Broker))
	b.WriteString(fmt.Sprintf("mqtt.client-id = %v\n", c.MQTT.ClientID))
	b.WriteString(fmt.Sprintf("mqtt.prefix = %v\n", c.MQTT.Prefix))
	b.WriteString(fmt.Sprintf("mqtt.username = %v\n", c.MQTT.Username))
	b.WriteString("mqtt.password = (redacted)\n")
	b.WriteString(fmt.Sprintf("image.projection = %v\n", c.Image.Projection))
	b.WriteString(fmt.Sprintf("image.fov = %v\n", c.Image.FOV))
	b.WriteString(fmt.Sprintf("image.format = %v\n", c.Image.Format))
	b.WriteString(fmt.Sprintf("image.width = %v\n", c.Image.Width))
	b.WriteString(fmt.Sprintf("image.height = %v\n", c.Image.Height))
	b.WriteString(fmt.Sprintf("image.stretch = %v\n", c.Image.Stretch))
	b.WriteString(fmt.Sprintf("image.min-cut = %v\n", c.Image.MinCut))
	b.WriteString(fmt.Sprintf("image.max-cut = %v\n", c.Image.MaxCut))
	b.WriteString(fmt.Sprintf("image.hips = %v\n", c.Image.HiPS))
	b.WriteString(fmt.Sprintf("cors-allowed-origins = %v\n", c.CORSAllowedOrigins))
	b.WriteString(fmt.Sprintf("public-frame.stacker-url = %v\n", c.PublicFrame.StackerURL))
	b.WriteString(fmt.Sprintf("public-frame.public-url = %v\n", c.PublicFrame.PublicURL))
	b.WriteString(fmt.Sprintf("public-frame.interval-seconds = %v\n", c.PublicFrame.IntervalSeconds))
	b.WriteString(fmt.Sprintf("public-frame.timeout-seconds = %v\n", c.PublicFrame.TimeoutSeconds))
	return b.String()
}
