name: Tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  checks: write

jobs:
  benchmark-tests:
    if: github.event_name != 'push' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - run: CGO_ENABLED=0 go test -run ^$ -benchmem -bench=. ./...

  race-tests:
    if: github.event_name != 'push' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Race tests
        run: go test ./... -race

  unit-tests:
    if: github.event_name != 'push' && github.ref != 'refs/heads/main'
    uses: ./.github/workflows/unit-test.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  unit-tests-coverage:
    permissions:
      contents: read
      checks: write
    uses: ./.github/workflows/unit-test.yaml
    with:
      coverage: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  coverage:
    needs: unit-tests-coverage
    if: ${{ !cancelled() }}
    permissions:
      contents: read
      pull-requests: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/coverage.yaml@c5ee15922a0ff4229b0f06a8d0551541b5cabfdc # v2.0.34
    with:
      artifact: coverage
      file: coverage.out
      app-id: ${{ vars.AUTO_COMMIT_APP_ID }}
    secrets:
      app-key: ${{ secrets.AUTO_COMMIT_APP_KEY }}
