name: Tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  checks: write

jobs:
  benchmark-tests:
    if: github.event_name != 'push' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: CGO_ENABLED=0 go test -run ^$ -benchmem -bench=. ./...

  race-tests:
    if: github.event_name != 'push' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Race tests
        run: go test ./... -race

  unit-tests:
    if: github.event_name != 'push' && github.ref != 'refs/heads/main'
    uses: ./.github/workflows/unit-test.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  unit-tests-coverage:
    permissions:
      contents: read
      checks: write
      pull-requests: write
    uses: ./.github/workflows/unit-test.yaml
    with:
      coverage: true
    secrets:
      auto_commit_app_key: ${{ secrets.AUTO_COMMIT_APP_KEY }}
      token: ${{ secrets.GITHUB_TOKEN }}
